/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_network_CustomSocketServer */

#ifndef _Included_com_study_network_CustomSocketServer
#define _Included_com_study_network_CustomSocketServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_network_CustomSocketServer
 * Method:    createServerSocket
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_study_network_CustomSocketServer_createServerSocket
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_study_network_CustomSocketServer
 * Method:    acceptConnection
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_study_network_CustomSocketServer_acceptConnection
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
